<?php
/**
 * 关于本站
 *
 * @package custom
 */
if (!defined('__TYPECHO_ROOT_DIR__')) { exit; }
?>
<?php $this->need('header.php'); ?>
<main class="mian-layout"><div class="about">
<h1 class="title">关于本站</h1>
<div class="about-content" style="grid-template-columns:3fr 2fr"><div class="about-item hello"><span class="text1">你好，很高兴认识你👋</span><span class="text2 title2"><?php $this->options->title(); ?></span><span class="text3">是一名独立开发者、博主和 Typecho 主题制作者</span></div><div class="about-item pursuit"><span class="tip">追求</span><span class="title2">源于</span><span class="title2">热爱而去开发</span><span class="title2">优秀的作品</span></div></div>
<div class="about-content" style="grid-template-columns:2fr 3fr"><div class="about-item skills"><span class="tip">技能</span><span class="title2">开启创造力</span><div class="skills-list"><a class="skills-item" style="--color:#f1e05a" href="https://developer.mozilla.org/zh-CN/docs/Web/JavaScript" target="_blank" rel="noopener"><div class="skills-logo"><i class="iconfont icon-javascript"></i></div><span class="skills-name">JavaScript</span></a><a class="skills-item" style="--color:#e34f26" href="https://developer.mozilla.org/zh-CN/docs/Web/HTML" target="_blank" rel="noopener"><div class="skills-logo"><i class="iconfont icon-html5"></i></div><span class="skills-name">HTML5</span></a><a class="skills-item" style="--color:#563d7c" href="https://developer.mozilla.org/zh-CN/docs/Web/CSS" target="_blank" rel="noopener"><div class="skills-logo"><i class="iconfont icon-css3"></i></div><span class="skills-name">CSS3</span></a><a class="skills-item" style="--color:#41b883" href="https://cn.vuejs.org/" target="_blank" rel="noopener"><div class="skills-logo"><i class="iconfont icon-vue"></i></div><span class="skills-name">Vue</span></a><a class="skills-item" style="--color:#149eca" href="https://react.dev/" target="_blank" rel="noopener"><div class="skills-logo"><i class="iconfont icon-react"></i></div><span class="skills-name">React</span></a></div></div><div class="about-item career"><span class="tip">生涯</span><span class="title2"><i>无限进步</i></span><div class="list"><span class="list-item" style="--color:#357ef5">前端开发 · Typecho 主题移植</span><span class="list-item" style="--color:#eb372a">独立开发 · 开源项目</span></div><img class="career-img" src="https://pic.efefee.cn/uploads/2024/02/22/65d71db18bcf9.png" alt="career"></div></div>
<div class="about-content" style="grid-template-columns:3fr 2fr"><div class="about-item character" style="--color:#4298b4"><span class="tip">性格</span><span class="title2">物流师</span><span class="title2" style="color:var(--color)">ISTJ-A / ISTJ-T</span><span class="more">在 <a href="https://www.16personalities.com/ch/" target="_blank" rel="noopener">16personalities</a> 了解更多关于 <a href="https://www.16personalities.com/ch/istj-%E4%BA%BA%E6%A0%BC" target="_blank" rel="noopener">物流师</a></span><img src="https://pic.efefee.cn/uploads/2024/02/22/65d6bc7ae72ae.png" alt="male" class="male"></div><div class="about-item"><span class="tip">座右铭</span><span class="title1" style="margin-top:20px">脚踏实地，</span><span class="title2">一丝不苟。</span></div></div>
<div class="about-content" style="grid-template-columns:1fr 1fr"><div class="about-item like image" style="--color:#0c0e20;background-image:url(https://pic.efefee.cn/uploads/2024/02/27/65dd812567723.webp)"><div class="image-content"><span class="tip">关注偏好</span><span class="title2">数码科技</span><div class="image-desc"><span class="left">手机、电脑及软硬件</span></div></div></div><div class="about-item like image" style="--color:#7b3c25;background-image:url(https://pic.efefee.cn/uploads/2024/02/27/65dd836099d16.webp)"><div class="image-content"><span class="tip">音乐偏好</span><span class="title2">欧美、华语流行、纯音乐、ACG</span><div class="image-desc"><span class="left">一起欣赏更多音乐</span></div></div></div></div>
<div class="about-content" style="display:flex"><div class="about-item"><span class="tip">心路历程</span><span class="title2">为什么建站？</span><p class="text">创建这个站，是为了有一个能够<strong>积累知识</strong>、<strong>积累兴趣</strong>并与他人分享的地方。如果能够帮助到更多的人，帮助更多人解决问题，那一定是非常棒的事情。</p><p class="text">这里大多都是<strong>技术向</strong>的文章，也会记录一些生活和思考。这些就是创造这个小站的本意，<strong>也是我分享生活的方式</strong>。</p></div></div>
</div>
<?php $this->need('footer.php'); ?>
